services:
  production:
    build:
      context: .
      dockerfile: site.Dockerfile
    ports:
      - "7001:7001"
    environment:
      - BASE_PATH=/rplib/
  staging:
    build:
      context: .
      dockerfile: staging.Dockerfile
    ports:
      - "7002:7001"
    environment:
      - BASE_PATH=/rplib_staging/
  dev:
    build:
      context: .
      dockerfile: dev.Dockerfile
    user: $USER
    ports:
      - "7003:7001"
    volumes:
      - ./data:/app/data
      - ./pyrplib:/app/pyrplib
      - ../ranking_toolbox/pyrankability:/app/pyrankability
      - ./site:/app/site
      - ./pipelines:/app/pipelines
    environment:
      - BASE_PATH=/rplib_dev/