services:
  site_dev:
    build:
      context: .
      dockerfile: site.Dockerfile
    user: $USER
    ports:
      - "7001:7001"
    volumes:
      - ./data:/app/data
      - ./pyrplib:/app/pyrplib
      - ./site:/app/site
      - ./pipelines:/app/pipelines
    environment:
        - BASE_PATH=/rplib/
